# 40-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mini-repo
  namespace: demo-eda
spec:
  selector:
    matchLabels:
      app: mini-repo
  endpoints:
  - port: http
    interval: 15s
    path: /metrics